language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

script: phpunit --configuration phpunit.travis.xml --coverage-text

notifications:
  hipchat:
    - secure: "DvXNjr6ckr04rPi3aMWjgRFbsYFqGUh0ZFPVmIv/HVzwP/VqEc3uMSjQKE/ZYM7sw5FhvLzvcBURfwe2bAReJKOPEHsSor9lhOyN6qUkGHj/DrHyNeQOvagAL494sisbYRkxYbxDuisfpydVZOZ8I+FdIrhxGJWLLilxzFF8hqQ="
